# Onboard vision
GEAR_CAMERA = 0
SHOOTER_CAMERA = 1
TARGETING_CAMERA_WIDTH = 424
TARGETING_CAMERA_HEIGHT = 240
TARGETING_CAMERA_FPS = 30
TARGETING_CAMERA_WHITE_BALANCE = 3000
TARGETING_CAMERA_BRIGHTNESS = -10
TARGETING_CAMERA_EXPOSURE = 20
TARGETING_LOWER_HSV_BOUND = (30, 108, 101)  # Tune this at each regional
TARGETING_UPPER_HSV_BOUND = (99, 255, 255)
TARGETING_SHOOTER_CENTER_KEY = 'shooter_target_details--center'
TARGETING_SHOOTER_FOUND_KEY = 'shooter_target_found'
