"""
config.py
=========
"""

import math

# Operator interface

OI_DRIVE_CONTROLLER = 0
OI_OPERATOR_CONTROLLER = 1

# Drive train

DRIVE_LEFT_MOTOR_MASTER = 0
DRIVE_LEFT_MOTOR_SLAVE = 1
DRIVE_RIGHT_MOTOR_MASTER = 2
DRIVE_RIGHT_MOTOR_SLAVE = 3

DRIVE_RIGHT_ENCODER_A = 4
DRIVE_RIGHT_ENCODER_B = 5
DRIVE_LEFT_ENCODER_A = 6
DRIVE_LEFT_ENCODER_B = 7
DRIVE_ENCODER_DISTANCE_PER_PULSE = (2 * math.pi * 4) / (256 * 3)
