"""
config.py
=========
"""

import math


IS_PRACTICE_BOT = False
NAVX_ENABLED = 'spi'

# 3/24 Vision disabled possibly causing roborio crash
FALLBACK_ONBOARD_VISION = False  # If Jetson comms issues

# Xbox controller consts
A_BUTTON = 1
B_BUTTON = 2
X_BUTTON = 3
Y_BUTTON = 4

# Operator interface

OI_DRIVE_CONTROLLER = 0
OI_SHIFT = 'left_bumper'
OI_DRIVER_DIRECTION = 'right_bumper'
OI_DRIVER_INTAKE = 'right_trigger'
OI_DRIVER_OUTTAKE = 'left_trigger'
OI_CLIMB = A_BUTTON

OI_TURRET_MANUAL_RIGHT = X_BUTTON
OI_TURRET_MANUAL_LEFT = B_BUTTON
OI_SHOOT_EDITABLE = Y_BUTTON

OI_OPERATOR_CONTROLLER = 1
OI_OP_FEED_IN = 'right_trigger'
OI_OP_FEED_OUT = 'left_trigger'
# OI_OP_TURRET_LEFT = 'left_bumper'
# OI_OP_TURRET_RIGHT = 'right_bumper'
OI_OP_INTAKE_GEAR = B_BUTTON
OI_OP_DEPOSIT_GEAR = X_BUTTON
OI_OP_LOWER_PLATE = Y_BUTTON
OI_OP_TURRET_MANUAL_RIGHT = 'right_bumper'
OI_OP_TURRET_MANUAL_LEFT = 'left_bumper'
OI_OP_SHOOT_EDITABLE = A_BUTTON

# Drive train

DRIVE_SENSITIVITY = 1
DRIVE_MAX_SPEED = 1
DRIVE_LEFT_MOTOR_MASTER = 6
DRIVE_LEFT_MOTOR_SLAVE = 5
DRIVE_RIGHT_MOTOR_MASTER = 9
DRIVE_RIGHT_MOTOR_SLAVE = 2

# ENCODER_CT = 128 if IS_PRACTICE_BOT else 256
# DRIVE_ENCODER_CODE_PER_REV = 4 * 3 * ENCODER_CT * (2/3)
# ENCODER_CT = 256 if IS_PRACTICE_BOT else 128
ENCODER_CT = 128
DRIVE_ENCODER_CODE_PER_REV = 4 * 2 * ENCODER_CT
DRIVE_ENCODER_DISTANCE_PER_REV = math.pi * 4  # inches
ENC_LEFT_FACTOR = DRIVE_ENCODER_DISTANCE_PER_REV * 4 * 2
ENC_RIGHT_FACTOR = 1

# DRIVE_ENCODER_DEGREES_PER_REV = 90 / 1.302  # deg / rotations
DRIVE_ENCODER_DEGREES_PER_REV = 90 / 1.55  # deg / rotations

DRIVE_SOLENOID_A = 4
DRIVE_SOLENOID_B = 5

# Climber
CLIMBER_MOTOR = 8

# Shooter
SHOOTER_MOTOR = 7
SHOOTER_FEEDER_MOTOR = 4

# Turret
TURRET_MOTOR = 3

# Floor intake
FLOOR_INTAKE_MOTOR = 1

# Gear manipulator
# GEAR_MANIPULATOR_ARTICULATING_PLATE_SOLENOID = 2
# GEAR_MANIPULATOR_ARTICULATING_CUP_SOLENOID = 3
GEAR_MANIPULATOR_ARTICULATING_PLATE_SOLENOID = 1
GEAR_MANIPULATOR_ARTICULATING_CUP_SOLENOID = 2

# Compressor
COMPRESSOR_DASHBOARD_KEY = 'editable--boolean--compressor'

# Misc
MISC_STARTING_POSITION_DASHBOARD_KEY = 'editable--chooser--starting_position'
MISC_AUTO_COMMAND_DASHBOARD_KEY = 'editable--chooser--autonomous_command'
MISC_DRIVER_DIRECTION_DASHBOARD_KEY = 'editable--chooser--driver_direction'
MISC_DRIVE_GEAR_DASHBOARD_KEY = 'driver_gear'
EDITABLE_RPM_KEY = 'editable--number--shooter_rpm'
