"""
config.py
=========
"""

# Operator interface

OI_DRIVE_CONTROLLER = 0
OI_OPERATOR_CONTROLLER = 1

OI_INTAKE = 'right_bumper'
OI_SHIFT = 'left_bumper'
OI_TURRET_RIGHT = 'right_trigger'
OI_TURRET_LEFT = 'left_trigger'
OI_SHOOT = 1  # "A" button
OI_CLIMB = 'start'

OI_DUMB_FEED = 2  # "B" button
OI_DUMB_SHOOT = 4  # "Y" button
OI_DUMB_FEED_OUT = 3  # "X" button

# Drive train

DRIVE_SENSITIVITY = 1
DRIVE_MAX_SPEED = 1
DRIVE_LEFT_MOTOR_MASTER = 2
DRIVE_LEFT_MOTOR_SLAVE = 9
DRIVE_RIGHT_MOTOR_MASTER = 5
DRIVE_RIGHT_MOTOR_SLAVE = 6

# DRIVE_ENCODER_CODE_PER_REV = (2 * math.pi * 4) / (256 * 3)
DRIVE_ENCODER_CODE_PER_REV = 256 * 3

DRIVE_SOLENOID_A = 4
DRIVE_SOLENOID_B = 5

# Climber
CLIMBER_MOTOR = 1

# Shooter
SHOOTER_MOTOR = 7
SHOOTER_FEEDER_MOTOR = 4

# Turret
TURRET_MOTOR = 3

# Floor intake
FLOOR_INTAKE_MOTOR = 8

# Gear manipulator
GEAR_MANIPULATOR_ARTICULATING_BOX_SERVO_A = 6
GEAR_MANIPULATOR_ARTICULATING_BOX_SERVO_B = 8
GEAR_MANIPULATOR_DOOR_SERVO = 9

# Compressor
COMPRESSOR_DASHBOARD_KEY = 'compressor'

# Misc
MISC_AUTO_COMMAND_DASHBOARD_KEY = 'editable--chooser--autonomous_command'
MISC_DRIVER_DIRECTION_DASHBOARD_KEY = 'editable--chooser--driver_direction'
MISC_DRIVE_GEAR_DASHBOARD_KEY = 'driver_gear'
