HOST = '0.0.0.0'
PORT = 5801

# DRIVER VISION
DRIVER_STREAM_INTERVAL = 0.02
DRIVER_STREAM_RETRY_INTERVAL = 0.5

# TARGETING
TARGETING_INTERVAL = 0.02
TARGETING_RETRY_INTERVAL = 0.5
TARGETING_CAMERA_WIDTH = 424
TARGETING_CAMERA_HEIGHT = 240
TARGETING_CAMERA_FPS = 30
TARGETING_CAMERA_WHITE_BALANCE = 3000
TARGETING_CAMERA_BRIGHTNESS = -10
TARGETING_CAMERA_EXPOSURE = 20
TARGETING_LOWER_HSV_BOUND = (30, 108, 101)  # Tune this at each regional
TARGETING_UPPER_HSV_BOUND = (99, 255, 255)

GEAR_TARGETING_CAMERA_PORT = 0
SHOOTER_TARGETING_CAMERA_PORT = 1


# NETWORK TABLES
# ROBOT_IP_ADDRESS = 'roborio-5045-frc.local'
ROBOT_IP_ADDRESS = '127.0.0.1'  # For development
NT_DRIVER_DIRECTION_SELECTOR = 'editable--chooser--driver_direction'
NT_AUTONOMOUS_COMMAND_SELECTOR = 'editable--chooser--autonomous_command'
